[package]
name = "wgpu-hello-example"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "wgpu hello example"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
publish = false

[dependencies]
env_logger.workspace = true
glam.workspace = true
log.workspace = true
pollster.workspace = true
wgpu.workspace = true

[dev-dependencies]
wgpu-test.workspace = true

