[package]
name = "wgpu-shadow-example"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "wgpu shadow example"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
publish = false

[dependencies]
bytemuck.workspace = true
glam.workspace = true
wasm-bindgen-test.workspace = true
wgpu-example.workspace = true
wgpu.workspace = true
winit.workspace = true

[dev-dependencies]
wgpu-test.workspace = true

