[package]
name = "wgpu-hello-triangle-example"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "wgpu hello triangle example"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
publish = false

[dependencies]
bytemuck.workspace = true
env_logger.workspace = true
pollster.workspace = true
wgpu.workspace = true
winit.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
wasm-bindgen-futures.workspace = true
web-sys.workspace = true
