[alias]
list-gpus = "run --bin wgpu-info -- -q"
xtask = "run --manifest-path xtask/Cargo.toml --"

[build]
rustflags = [
"--cfg=web_sys_unstable_apis"
]
rustdocflags = [
"--cfg=web_sys_unstable_apis"
]
