[package]
name = "wgpu-water-example"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "wgpu water example"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
autotests = false
publish = false


[dependencies]
wgpu-example = { path = "../common" }
wgpu = { path = "../../wgpu" }

[dev-dependencies]
wgpu-test = { path = "../../tests" }
