[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "hlsl-snapshots"
publish = false
version = "0.1.0"

[lib]
name = "hlsl_snapshots"
path = "src/lib.rs"
test = false

[dependencies]
anyhow = "1"
nanoserde = "0.1.37"
