[package]
name = "wgpu-core"
version = "0.5.0"
authors = ["wgpu developers"]
edition = "2018"
description = "WebGPU core logic on gfx-hal"
homepage = "https://github.com/gfx-rs/wgpu"
repository = "https://github.com/gfx-rs/wgpu"
keywords = ["graphics"]
license = "MPL-2.0"

[lib]

[features]
default = []
# Enable API tracing
trace = ["ron", "serde", "wgt/trace"]
# Enable API replaying
replay = ["serde", "wgt/replay"]
# Enable serializable compute/render passes, and bundle encoders.
serial-pass = ["serde", "wgt/serde", "arrayvec/serde"]
# Enable chrome-tracing backend and default tracing subscriber
subscriber = ["chrono", "once_cell", "thread-id", "tracing-log", "tracing-subscriber"]

[dependencies]
arrayvec = "0.5"
bitflags = "1.0"
chrono = { version = "0.4", optional = true }
copyless = "0.1"
fxhash = "0.2"
log = "0.4"
hal = { package = "gfx-hal", version = "0.5.2" }
gfx-backend-empty = "0.5"
once_cell = { version = "1", optional = true }
parking_lot = "0.10"
raw-window-handle = { version = "0.3", optional = true }
ron = { version = "0.5", optional = true }
serde = { version = "1.0", features = ["serde_derive"], optional = true }
smallvec = "1"
spirv_headers = { version = "1.4.2" }
thread-id = { version = "3", optional = true }
tracing = { version = "0.1", default-features = false, features = ["std"] }
tracing-log = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.2", default-features = false, optional = true, features = ["env-filter", "registry"] }
vec_map = "0.8.1"

[dependencies.naga]
git = "https://github.com/gfx-rs/naga"
rev = "a9228d2aed38c71388489a95817238ff98198fa3"

[dependencies.gfx-descriptor]
git = "https://github.com/gfx-rs/gfx-extras"
rev = "438353c3f75368c12024ad2fc03cbeb15f351fd9"

[dependencies.gfx-memory]
git = "https://github.com/gfx-rs/gfx-extras"
rev = "438353c3f75368c12024ad2fc03cbeb15f351fd9"

[dependencies.wgt]
path = "../wgpu-types"
package = "wgpu-types"
version = "0.5"

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
gfx-backend-metal = { version = "0.5.4" }
gfx-backend-vulkan = { version = "0.5.6", optional = true }

[target.'cfg(all(unix, not(target_os = "ios"), not(target_os = "macos")))'.dependencies]
gfx-backend-vulkan = { version = "0.5.6" }

[target.'cfg(windows)'.dependencies]
gfx-backend-dx12 = { version = "0.5.6" }
gfx-backend-dx11 = { version = "0.5" }
gfx-backend-vulkan = { version = "0.5.8" }

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "windows", target_os = "dragonfly", target_os = "freebsd"))'.dependencies]
battery = { version = "0.7", optional = true }

[dev-dependencies]
loom = "0.3"
